apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ai.clipper.container.label: {{ cluster_name }}
    ai.clipper.name: redis
  name: redis-at-{{ cluster_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      ai.clipper.container.label: {{ cluster_name }}
      ai.clipper.name: redis
  template:
    metadata:
      labels:
        ai.clipper.container.label: {{ cluster_name }}
        ai.clipper.name: redis
    spec:
      containers:
      - args:
        - redis-server
        - --port
        - "6379"
        image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always
